version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: m1pes
      POSTGRES_USER: m1pes-user
      POSTGRES_PASSWORD: m1pepass
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"